### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by dungphanxuan** [dungphanxuan/yii2-starter-kit-lite#1]
Todo for app
- [x] Login, register api
- [ ] Login, register api for social account
- [ ] Speed App
- [ ] Demo for feature
- [ ] Write document

**Comment by dungphanxuan** [comment]
Add article pickup reference b80d72ac2b4692914580d61d2bcc0a50a3bcea4c
